[config]
transactions = 10000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "Shreder binary"
url = "http://fra.binary.shreder.xyz:9991/"
kind = "shreder"


[[endpoint]]
name = "Corvus aRpc"
url = "http://arpc.fra.corvus-labs.io:20202"
kind = "arpc"
